version: '2'
services:
  log:
    container_name: cargo_log
    image: cargo.caicloud.io/cargo/cargo_log:latest
    restart: always
    volumes:
      - /data/log/harbor/:/var/log/docker/
    ports:
      - 1514:514
  registry:
    container_name: cargo_registry
    image: cargo.caicloud.io/cargo/cargo_registry:latest
    restart: always
    volumes:
      - /data/registry:/storage
      - ../common/config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  mysql:
    container_name: cargo_mysql
    image: cargo.caicloud.io/cargo/cargo_mysql:latest
    restart: always
    volumes:
      - /data/database:/var/lib/mysql
    # for debug
    # ports:
    #   - 3306:3306
    env_file:
      - ../common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
  ui:
    container_name: cargo_ui
    image: cargo.caicloud.io/cargo/cargo_ui:latest
    env_file:
      - ../common/config/ui/env
    restart: always
    volumes:
      - ../common/config/ui/app.conf:/etc/ui/app.conf
      - ../common/config/ui/private_key.pem:/etc/ui/private_key.pem
    environment:
      - CLAIR_SERVER_IP=clair:6060
    depends_on:
      - log
    links:
      - clair
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
  jobservice:
    container_name: cargo_jobservice
    image: cargo.caicloud.io/cargo/cargo_jobservice:latest
    env_file:
      - ../common/config/jobservice/env
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs
      - ../common/config/jobservice/app.conf:/etc/jobservice/app.conf
    depends_on:
      - ui
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  proxy:
    container_name: cargo_proxy
    image: cargo.caicloud.io/cargo/cargo_proxy:latest
    restart: always
    volumes:
      - ../common/config/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"

  cleaner:
    container_name: cargo_cleaner
    image: cargo.caicloud.io/cargo/cargo_cleaner:latest
    restart: always
    tty: true
    volumes:
      - ./cleaner/cleaner.py:/cleaner.py
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "cleaner"

  postgres:
    container_name: cargo_postgres
    image: cargo.caicloud.io/cargo/cargo_postgres:latest
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    # for debug
    # ports:
    #  - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "postgres"

  clair:
    container_name: cargo_clair
    image: cargo.caicloud.io/cargo/cargo_clair:latest
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./config/clair:/config
    command: [-config, /config/config.yaml]
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair"
