apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
  namespace: harbor
  labels:
    name: mysql-rc
spec:
  replicas: 1
  selector:
    name: mysql-apps
  template:
    metadata:
      namespace: harbor
      labels:
        name: mysql-apps
    spec:
      containers:
      - name: mysql-app
        image: test.caicloud.io/harbor/mysql:0.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root123
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: storage-pvc 
