apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: log
